{% set version = "2024.9.11" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 6c188c307e8433bcb63dc1915022deb553b4203a70722fc542c363bf120a01fd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  # https://bitbucket.org/mrabarnett/mrab-regex/issues/124/please-add-a-license-file-to-the-package
  license: Python-2.0
  license_file: LICENSE.txt
  license_family: PSF
  summary: Alternative regular expression module, to replace re

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
