{% set name = "regex" %}
{% set version = "2026.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/regex-{{ version }}.tar.gz
  sha256: 6fb8cb09b10e38f3ae17cc6dc04a1df77762bd0351b6ba9041438e7cc85ec310

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >77.0.3
    - pip
  run:
    - python

test:
  imports:
    - regex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrabarnett/mrab-regex
  license: Apache-2.0 AND CNRI-Python
  license_file: LICENSE.txt
  license_family: PSF
  summary: Alternative regular expression module, to replace re

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
