{% set version = "2019.12.18" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 70350f64502ed58428aa4407509737f2fbdb8d0ceda3f58282eba1c26a11cd69

build:
  number: 0
  skip: True  # [win and py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  # https://bitbucket.org/mrabarnett/mrab-regex/issues/124/please-add-a-license-file-to-the-package
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
