{% set version = "2020.2.20" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 9e9624440d754733eddbcd4614378c18713d2d9d0dc647cf9c72f64e39671be5

build:
  number: 1
  skip: True  # [win and py27]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  # https://bitbucket.org/mrabarnett/mrab-regex/issues/124/please-add-a-license-file-to-the-package
  license: Python-2.0
  license_family: PSF
  summary: 'Alternative regular expression module, to replace re'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
