{% set version = "2024.7.24" %}

package:
  name: regex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/regex/regex-{{ version }}.tar.gz
  sha256: 9cfd009eed1a46b27c14039ad5bbc5e71b6367c5b2e6d5f5da0ea91600817506

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - regex

about:
  home: https://bitbucket.org/mrabarnett/mrab-regex
  # https://bitbucket.org/mrabarnett/mrab-regex/issues/124/please-add-a-license-file-to-the-package
  license: Python-2.0
  license_file: LICENSE.txt
  license_family: PSF
  summary: Alternative regular expression module, to replace re

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - xhochy
